import fs from 'fs';
import { createClient } from '@supabase/supabase-js';

const envFile = fs.readFileSync('.env', 'utf-8');
const env = {};
envFile.split('\n').forEach(line => {
  const [key, ...value] = line.split('=');
  if (key && value.length > 0) {
    env[key.trim()] = value.join('=').trim().replace(/['"]/g, '');
  }
});

const supabaseUrl = env['VITE_SUPABASE_URL'];
const supabaseKey = env['VITE_SUPABASE_ANON_KEY'];

const supabase = createClient(supabaseUrl, supabaseKey);

const rawData = `A A FRIGELAR MOTO REFRIGERACAO LTDA	R GENERAL ARGOLO, 15 - 	RIO DE JANEIRO	RJ
A GERADORA ALUGUEL DE MAQUINAS S.A.	RODOVIA WASHINGTON LUIZ, 13501 - FIGUEIRA	Duque de Caxias	RJ
A. TAVARES CARPINTARIA E MARCENARIA	AV GUADALAJARA, 1782 - 	MACAE	RJ
A2B	RUA JUMECY RODRIGUES GOMES, 380 - D	PIRAI	RJ
ABC REVESTIMENTOS	AVENIDA AYRTON SENNA, 3383 - LOJA 102 E 103	RIO DE JANEIRO	RJ
ABELV ENGENHARIA LTDA	RUA FERNANDO FALCÃO, 1111 - 9º ANDAR	São Paulo	SP
AC&F SERVICOS TECNICOS LTDA	AVENIDA CAMILO CASTELO BRANCO, 90 - 	SÃO PAULO	SP
AEL SISTEMAS S.A	AVENIDA SERTÓRIO, 4400 - 	Porto Alegre	RS
AFTON CHEMICAL INDUSTRIA DE ADITIVOS LTDA	ESTRADA DA BOA ESPERANÇA, 650 - PARTE	BELFORD ROXO	RJ
ÁGUAS DO RIO 1 SPE S.A	AVENIDA RODRIGUES ALVES, 10 - ARM 02 BL 1 E 4	RIO DE JANEIRO	RJ
ÁGUAS DO RIO 4 SPE S.A	AVENIDA RODRIGUES ALVES, 10 - ARM 2 BL 1 E 4	RIO DE JANEIRO	RJ
AGUIA SISTEMAS DE ARMAZENAGEM LTDA	AV SENADOR FLAVIO CARVALHO GUIMARAES, 3505 - 	PONTA GROSSA	PR
AIR LIQUIDE BRASIL LTDA	RUA LÉA ARANHA, 650 - 	BELFORD ROXO	RJ
AIR LIQUIDE BRASIL LTDA	AV JOAO XXIII, S/ N - PARTE	RIO DE JANEIRO	RJ
AIR LIQUIDE BRASIL LTDA - FILIAL SUZANO	AVENIDA JORGE BEI MALUF, 2125 - 	SUZANO	SP
ALCABRAS EQUIPAMENTOS INDUSTRIAIS EIRELI	RUA ARGENTINA GRILLO BADIA, 871 - BRCAO	SERTÃOZINHO	SP
ALICE EDUARDA E DAVI COMERCIO E SERVICOS NAVAIS E INDUSTRIAIS EIRELI	TRAVESSA HEITOR MENDONÇA, 248 - CASA 1	SÃO GONÇALO	RJ
ALLONDA AMBIENTAL S.A.	ALAMEDA MAMORÉ, 503 - CONJ 23 E 24	BARUERI	SP
AMPERTEC SOLUCOES E COMERCIO DE MATERIAIS ELETRICOS E HIDRAULICOS LTDA	RUA LONDRES, 327 - LOJA A	BELFORD ROXO	RJ
AMPLA ENERGIA E SERVICOS S.A.	AVENIDA OSCAR NIEMEYER, 01 - SALA 701	RIO DE JANEIRO	RJ
ANDRADE & SANTOS	ALAMEDA ARMENIO MENDES, 66 - SALA 905	SANTOS	SP
ANGETEC SOLUCOES TECNICAS INDUSTRIAL EIRELI ME	RUA SEIS,  - S/N QD LT 3 GALPAO 1	ITAGUAÍ	RJ
ANTENOR VERONA & CIA LTDA	AVENIDA MARGINAL, 465 - 	VISTA ALEGRE DO ALTO	SP
APERONIA TRANSPORTES	,  - 		
ARCOL CONSTRUCOES METALICAS EIRELI	RUA JÚLIO DIONÍSIO CARDOSO, 860 - 	JUIZ DE FORA	MG
ARES AEROESPACIAL E DEFESA S/A	ESTRADA SÃO MATEUS, 293 - 	DUQUE DE CAXIAS	RJ
ARFLEX AR CONDICIONADO	AVENIDA PEDRA BRANCA, 1325 - APT 303	PALHOCA	SC
ARSENAL DE MARINHA DO RIO DE JANEIRO	PRAÇA BARÃO DE LADÁRIO, SN - 	RIO DE JANEIRO	RJ
ARTHUR PEIXOTO	RUA MARITUBA, 441 - 	RIO DE JANEIRO	RJ
ASM	RUA CANDELARIA, 00079 - SAL 803	RIO DE JANEIRO	RJ
ASSOCIACAO CONGREGACAO DE SANTA CATARINA	RUA PAULINO AFONSO, 477 - 	PETRÓPOLIS	RJ
ASSOCIACAO DE APOIO A ESCOLA CIEP 486 P LUIZ VALLEJO	ESTRADA GOVERNADOR CHAGAS FREITAS, 798 - 	BARRA MANSA	RJ
AUTO-ENERGY MANUTENCAO E INSTALACAO INDUSTRIAL LTDA	R SARGENTO MAURO MARQUES DA SILVA, 80 - 	CAMPINAS	SP
AUTOMATION SECURITY AND SERVICES LTDA	ESTRADA DO CERCADINHO, 1190 - 	BELO HORIZONTE	MG
B5 CONSTRUTORA LTDA	RUA GEMINIANO LABRE, 21 - 	Rio de Janeiro	RJ
BALPRENSA COMERCIO E INDUSTRIA DE FERRO LTDA	AVENIDA COELHO DA ROCHA, 1196 - 	MESQUITA	RJ
BASE AEREA DE SANTOS	AVENIDA CASTELO BRANCO, S/N - 	GUARUJÁ	SP
BASE DE ABASTECIMENTO DA MARINHA - RJ	AVENIDA BRASIL, 10500 - 	RIO DE JANEIRO	RJ
BASE DE FUZILEIROS NAVAIS DA ILHA DAS FLORES	RUA ACRE, SN - ILHA DAS FLORES	SÃO GONÇALO	RJ
BASE DE SUBMARINOS DA ILHA DA MADEIRA	ESTRADA PREFEITO WILSON PEDRO FRANCISCO, S/N - 	ITAGUAI	RJ
BASE NAVAL DO RIO DE JANEIRO	ILHA MOCANGUÊ GRANDE, S/N,  - 	NITERÓI	RJ
BAYER S.A.	ESTRADA DA BOA ESPERANÇA, 650 - 	BELFORD ROXO	RJ
BELLUNO VEICULOS LTDA	AVENIDA DAS MISSÕES,  - 	RIO DE JANEIRO	RJ
BELOV ENGENHARIA LTDA	ESTRADA MARTHA ALCÂNTARA FARES, 3000 - LOTE 40	Guapimirim	RJ
BIO G SISTEMAS DE SANEAMENTO LTDA	RODOVIA SC 150, 1000 - P. 08 E 09	CAPINZAL	SC
BMB LOG SERVICOS LOGISTICOS E TRANSPORTES LTDA	RODOVIA WASHINGTON LUIZ, 3968 - 	Duque de Caxias	RJ
BR MARINAS GLORIA S.A.	AVENIDA INFANTE DOM HENRIQUE, SN - LOJA 03 - G	RIO DE JANEIRO	RJ
BRAL INDUSTRIA	RUA VELASQUES, LT 10 - QUADRA S PLANO B	JAPERI	RJ
BRASIL AO CUBO S/A	RUA DÁRIO ANACLETO LINHARES, 26 - 	Tubarão	SC
BRASIL PROJECTS TRANSPORTES NACIONAIS E INTERNACIONAIS LTDA	AVENIDA CIDADE JARDIM, 377 - ANDAR 8 SALA A	SÃO PAULO	SP
BRK AMBIENTAL - MACAE S/A	AVENIDA RUI BARBOSA, 1011 - APTO 601	MACAÉ	RJ
BRZ EMPREENDIMENTOS PORTAL ALTOS DE AQUARIUS SPE LTDA	ROD AMARAL PEIXOTO, 283 - QUADRA32 LOTE 4 KM 107	SAO PEDRO DA ALDEIA	RJ
BRZ EMPREENDIMENTOS PORTAL RECANTO DOS SABIAS SPE LTDA	RODOVIA WASHINGTON LUIZ, 14005 - 	DUQUE DE CAXIAS	RJ
C. D. A. MONTAGENS INDUSTRIAIS LTDA	AVENIDA JOSÉ GALLI, 140 - 	ARARAQUARA	SP
C.R.TECHNOLOGY SYSTEMS S.P.A.	VIA CRESCENZIO, 82 - 		
CAM ENGENHARIA E SERVICOS LTDA	RUA SOTER RAMOS COUTO, 44 - SALA 801	BELO HORIZONTE	MG
CAPROCK COMUNICAÇÕES	AV PREFEITO ARISTEU FERREIRA DA SILVA, 2600 - 	MACAE	RJ
CARL ZEISS VISION BRASIL INDUSTRIA OPTICA LTDA	RUA LUIZ WINTER, 222 - 	PETRÓPOLIS	RJ
CARLOS AUGUSTO MARTINS	,  - 		
CASAS GUANABARA	AV DOM HELDER CAMARA, 8403 - 8433/R.DIV.SALVADOR	RIO DE JANEIRO	RJ
CASAS GUANABARA COMESTIVEIS LTDA	ESTRADA DA ÁGUA BRANCA, 3400 - 	RIO DE JANEIRO	RJ
CASAS GUANABARA COMESTIVEIS LTDA	R BELEM, 160 - E 160	RIO DE JANEIRO	RJ
CB RIO NORTE SHOPPING COMERCIO DE ALIMENTOS LTDA	AVENIDA DOM HÉLDER CÂMARA, 5474 - LOJAS 5102A, 5102B	RIO DE JANEIRO	RJ
CENTRAIS ELETRICAS DO NORTE DO BRASIL S/A	SEPN 504 BLOCO D,  - CENTRO CORPORATIVO PORTINARI	BRASÍLIA	DF
CENTRAIS ELETRICAS DO NORTE DO BRASIL S/A ELETRONORTE	RUA GERALDO PRATES, SN - UHE TUCURUI	TUCURUÍ	PA
CENTRAL DE TRATAMENTO DE RESIDUOS NOVA IGUACU S.A.	ESTRADA ADRIANÓPOLIS, 5213 - 	NOVA IGUAÇU	RJ
CENTRO DE DISTRIBUICAO DE UNIFORMES-COM1 DNA	PRAÇA BARÃO DE LADÁRIO, SN - COMPLEXO 1 DIST NAVAL	RIO DE JANEIRO	RJ
CENTRO DE MEDICINA OPERATIVA DA MARINHA	AVENIDA DOM HÉLDER CÂMARA, 315 - 	RIO DE JANEIRO	RJ
CET LOGISTICS AGENTE DE CARGA E TRANSPORTE LTDA	RUA PEDRO ALVES, 307 - 	RIO DE JANEIRO	RJ
CLEMAR ENGENHARIA LTDA	RUA GUATEMALA, 228 - 	RIO DE JANEIRO	RJ
CLUBE NAVAL	AVENIDA CARLOS ERMELINDO MARINS, 68 - 	NITERÓI	RJ
CME COMÉRCIO DE MÁQUINAS E EQUIPAMENTOS LTDA	AVENIDA BRASIL,  - 	Rio de Janeiro	RJ
COCO BAMBU RIO RECREIO DOS BANDEIRANTES	AV DAS AMERICAS, 19021 - LOJAS 201 INTERNAMENTE 205B16 PARTE PISO L2	RIO DE JANEIRO	RJ
COFANI SUCATAS	RUA FRANCISCO CHAVES PINHEIRO, 69 - CASA 1	SAO PAULO	SP
COMANDO DA MARINHA DEPOSITO NAVAL RJ	AVENIDA BRASIL, 10500 - 	RIO DE JANEIRO	RJ
COMPANHIA DISTRIBUIDORA DE GAS DO RIO DE JANEIRO - CEG	RUA SÃO CRISTÓVÃO, 1200 - 	Rio de Janeiro	RJ
COMPANHIA DOCAS DO RIO DE JANEIRO	RUA ACRE, 21 - LJS A B 2 AO 12 PAV	RIO DE JANEIRO	RJ
COMPANHIA DOREL BRASIL PRODUTOS INFANTIS	AVENIDA DOUTOR NILO PEÇANHA, 1516 - 	CAMPOS DOS GOYTACAZES	RJ
COMPANHIA RIOGRANDENSE DE SANEAMENTO - CORSAN	RUA CALDAS JÚNIOR, 120 - 	PORTO ALEGRE	RS
COMTRAFO INDUSTRIA DE TRANSFORMADORES ELETRICOS S.A	EST CHACARA PARAISO, SN - 	CORNÉLIO PROCÓPIO	PR
COMTRAFO INDUSTRIA DE TRANSFORMADORES ELETRICOS S.A.	AV AGOSTINHO DUCCI, 280 - 	CORNÉLIO PROCÓPIO	PR
CONCESSIONARIA DO VLT CARIOCA S.A	RUA DA UNIÃO, 11 - GAMBOA	RIO DE JANEIRO	RJ
CONDOMINIO CENTRO EMPRESARIAL SENADO	AVENIDA HENRIQUE VALADARES, 28 - 	RIO DE JANEIRO	RJ
CONDOMINIO DO EDIFICIO BARAO DE JAVARY	RUA DA AJUDA, 35 - EM FRENTE AO METRÔ DA CARIOCA	RIO DE JANEIRO	RJ
CONDOMINIO DO EDIFICIO RESIDENCIAS GOLF CLUB	AVENIDA PREFEITO MENDES DE MORAIS, 1010 - 	RIO DE JANEIRO	RJ
CONDOMINIO DO VIA BRASIL SHOPPING RIO	RUA ITAPERA, 500 - 	Rio de Janeiro	RJ
CONDOMINIO DO WEST SHOPPING - RIO	EST DO MENDANHA, 555 - 	RIO DE JANEIRO	RJ
CONE ENGENHARIA E CONSTRUCAO CIVIL LTDA	RUA SENADOR DANTAS, 7 - 	RIO DE JANEIRO	RJ
CONENGE	ESTRADA NOVA DE MAUA, 891 - QUADRAF	MAGE	RJ
CONENGE-SC CONSTRUCOES E ENGENHARIA S/A	AVENIDA AGC BARRA DO FURADO, 0 - 	QUISSAMA	RJ
CONFAB INDUSTRIAL S/A.	RUA DOUTOR GONZAGA, 1381 - 	PINDAMONHANGABA	SP
CONSAG CS S.A	AVENIDA BRASIL, 41920 - SALA 10	RIO DE JANEIRO	RJ
CONSORCIO ACTEMIUM ECB / ESFERAS - MATRIZ	VIA EXPRESSA FRANCISCO CLEUTON LOPES, 3850 - SALA1A	CONTAGEM	MG
CONSORCIO CONSTRUTOR RODOVIA BR 493	R YAMAGATA, 193 - GALPAO1A	ITABORAI	RJ
CONSORCIO ECB LCD REDUC	RUA AILTON DA COSTA, 115 - SALA 512	RIO DE JANEIRO	RJ
CONSORCIO PARKJACAREPAGUA	ESTRADA DE JACAREPAGUÁ, 6069 - 	RIO DE JANEIRO	RJ
CONSORCIO POSSEBON/UPE/CPL - EPC 13	AV VINTE E DOIS DE MAIO, 5990 - BLOCO 02 SALA 102	ITABORAI	RJ
CONSTRUTECKMA ENGENHARIA LTDA.	AVENIDA PAES DE BARROS, 2694 - 	SÃO PAULO	SP
CONSTRUTORA APICE LTDA	RUA MANUEL DE ABREU, 121 - 	ITAGUAÍ	RJ
CONTROAR	RUA JOAQUIM PINHEIRO, 00311 - FDS ANT CAS 1	RIO DE JANEIRO	RJ
COPARTS COMERCIAL DE PECAS E SERVICOS LTDA	R DR. AFONSO VERGUEIRO, 568 - 	SAO PAULO	SP
CORBION	AV RUI BARBOSA, 521 - 	CAMPOS DOS GOYTACAZES	RJ
CORBION PRODUTOS RENOVAVEIS LTDA	FAZENDA MOEMA, SN - 	ORINDIÚVA	SP
CORPORAÇÃO  BRASILEIRA DE TRANSFORMADORES	RUA IWAGIRO TOYAMA, 1200 - 	SAO PAULO	RJ
CRAFT ENGENHARIA LTDA	ESTRADA DO PEDREGOSO, 2689 - 	RIO DE JANEIRO	RJ
CRM IND E COM DE ALIMENTOS LTDA - KOPENHAGEN	RODOVIA FERNAO DIAS, SN - KM 938	EXTREMA	MG
CROACIA MOVIMENTACAO E ELEVACAO DE CARGAS	R SIMAO KOSSOBUDSKI, 917 - 	CURITIBA	PR
CRONOS INDUSTRIA E COMERCIO DE EQUIPAMENTOS INDUSTRIAIS E SERVICOS DA	AVENIDA MONTEIRO LOBATO, 2363 - GALPAO 2	GUARULHOS	SP
CRR	AVENIDA SENADOR VITORINO FREIRE, 365 - GALPAO	RIO DE JANEIRO	RJ
CYMI O&M LTDA	ÁREA RURAL, S/N - 	JUAZEIRO	BA
CYRELA RJZ CONSTRUTORA E EMPREENDIMENTOS IMOBILIARIOS LTDA	RUA DO ROCIO, 109 - 	SÃO PAULO	SP
CYRJZ CYRELA - MATRIZ	RUA DO ROCIO, 109 - ANDAR 03SALA01PARTE	São Paulo	SP
D.A.S ENGENHARIA LTDA	RUA SETE DE SETEMBRO, 99 - SALA 201	RIO DE JANEIRO	RJ
DANGELI PROJETOS E CONSTRUCOES LTDA	AV GENERAL OLYNTHO PILLAR, 355 - APT 206 BLC 1	RIO DE JANEIRO	RJ
DATA ENGENHARIA LTDA	RUA SAO JUDAS TADEU, 280 - 	SARZEDO	MG
DATAPREV	ST DE AUTARQUIAS SUA , QUADRA, 01 - BLOCOS E/F - PARTE	BRASILIA	DF
DEFENSORIA PUBLICA DO ESTADA DO PARÁ	TRAVESSA PADRE PRUDÊNCIO, 154 - 	BELÉM	PA
DEFENSORIA PUBLICA DO ESTADO DO RIO DE JANEIRO-DPE	AVENIDA MARECHAL CÂMARA, 314 - 	RIO DE JANEIRO	RJ
DELTA INSPECOES SOLUCOES DE ENGENHARIA	R ALBERTO SIQUEIRA, 1065 - LOTE 32 LOTE 33	DUQUE DE CAXIAS	RJ
DEMOLIDORA SOLUM	R MAJOR DELFINO DE PAULA, 2450 - 	BELO HORIZONTE	MG
DENSITEL TRANSFORMADORES LTDA	RODOVIA ENGENHEIRO RENÊ BENEDITO DA SILVA, 1065 - 	ITAPEVI	SP
DESA ENGENHARIA E REFRATARIOS LTDA	RUA JOAO PEREIRA LIMA, 90 - 	MATOZINHOS	MG
DIEGO DE SOUZA SILVA	RUA JOSÉ VIEIRA DA COSTA, 243 - LOTE 18 QUADRA 35	MAGÉ	RJ
DIFFUCAP - CHEMOBRAS QUIMICA E	RUA GOIÁS, 1232 - 	RIO DE JANEIRO	RJ
DIGISENSOR SISTEMAS DE SEGURANCA LTDA	RUA MERGENTHALER, 232 - 	SÃO PAULO	SP
DIVERTPLAN	AVENIDA DAS AMERICAS, 4200 - BLOCO 02 SALA 501 PARTE	RIO DE JANEIRO	RJ
DN4 TECNOLOGIA SOLUÇOES E SERVIÇOS LTDA	RUA BORGES LAGOA, ND - 	SÃO PAULO	SP
DOUBLE CAR LOCADORA DE VEICULOS E EQUIPAMENTOS LTDA	RUA OCEANO ATLÂNTICO, 1313 - SALA 2	CAMBÉ	PR
DRX SERVICOS TECNICOS	RUA SAO JANUARIO, 153 - LOJA LETRA I	RIO DE JANEIRO	RJ
DVICTOR TRANSPORTES LTDA - GELMUNCK	RUA PEREIRA PASSOS, 6 - 	DUQUE DE CAXIAS	RJ
EASE ENGENHARIA LTDA	AVENIDA ALMIRANTE ADALBERTO DE BARROS NUNES, 1900 - 	VOLTA REDONDA	RJ
EBMAC TRANSPORTES E LOGISTICA LTDA	AVENIDA CARMELA DUTRA, 180 - 	GUARULHOS	SP
EBSE ENGENHARIA DE SOLUCOES S.A	AVENIDA DE SANTA CRUZ, 10280 - 	RIO DE JANEIRO	RJ
ECOGEN RIO SOLUÇÕES ENERGETICAS S.A	RUA ANDRÉ ROCHA, 2299 - 	RIO DE JANEIRO	RJ
EDITORA GLOBO S/A	RODOVIA WASHINGTON LUIZ, 3000 - 	DUQUE DE CAXIAS	RJ
ELECOMTEC	R OURIQUE, 62 - GALPAO	RIO DE JANEIRO	RJ
ELETRICA TEMPERMAR LTDA	R IGUAPERIBA, 00500 - A	RIO DE JANEIRO	RJ
ELETROBRAS ELETRONUCLEAR S.A	RUA CANDELÁRIA, 65 - 2º AO 10º 12º E 19º ANDARES	RIO DE JANEIRO	RJ
ELETROBRAS ELETRONUCLEAR S/A	RODOVIA PROCURADOR HAROLDO FERNANDES DUARTE, SN - KM 521.56	ANGRA DOS REIS	RJ
ELETROBRAS JACAREPAGUA	ESTRADA PAU DA FOME, 00839 - 	RIO DE JANEIRO	RJ
ELETROMECANICA SAO JORGE LTDA	RUA DOUTOR MILTON LADEIRA, 285 - 	Juiz de Fora	MG
ELTONS ELIAS	 AV BRASIL, 10102 - 	RIO DE JANEIRO	RJ
EMPREITEIRA PAULISTANA ENGENHARIA E CONSTRUCOES LTDA	ESTRADA DO OTAVIANO, 551 - 	Rio de Janeiro	RJ
EMPRERMAC EQUIPAMENTOS INDUSTRIAIS LTDA	AVENIDA AFONSO TRIGO, 241 - SALA 01	SERTAOZINHO	SP
EMPRESA BRASILEIRA DE INFRAESTRUTURA AEROPORTUARIA - INFRAERO	PRAÇA SENADOR SALGADO FILHO, SN - 	RIO DE JANEIRO	RJ
EMPRESA BRASILEIRA DE REPAROS NAVAIS S A RENAVE	ILHA DO VIANA, S/N - 	NITEROI	RJ
EMPRESA DE TRANSPORTE ANGELA LTDA (PORFILIO)	RUA GUARAUNA, 306 - GALPÃO	RIO DE JANEIRO	RJ
EMPRESA GERENCIAL DE PROJETOS NAVAIS - ENGEPRON	ILHA DAS COBRAS, SN - 	RIO DE JANEIRO	RJ
ENERFLEX BRASIL ENERGIA LTDA	RUA DOS POLÍMEROS, 1 - ST IND LESTE	CAMAÇARI	BA
ENGECAMPO ENGENHARIA S/A	ESTRADA VELHA DO PILAR, SN - LOTE 08 QUADRA2E SALA 201	Duque de Caxias	RJ
ENGEKO ENGENHARIA E CONSTRUÇÃO LTDA	RUA FRANÇA PINTO, 1347 - 	SÃO PAULO	SP
ENGEMOLDE ENGENHARIA, INDUSTRIA E COMERCIO LTDA.	RODOVIA ERNANI DO AMARAL PEIXOTO, SN - 	MARICÁ	RJ
ENGEMON COMERCIO E SERVIÇOS TECNICOS LTDA	AVENIDA DOUTORA RUTH CARDOSO, 4777 - CONJ 111 E 112 ANDAR 1	SÃO PAULO	SP
ENGEPARK OBRAS E SERVICOS LTDA	RUA FRANCISCO EUGÊNIO 00268, 00268 - SAL 0236 SAL 0237	Rio de Janeiro	RJ
EPASA SERVICOS TECNICOS LTDA	RUA 08, 04 - 	NITEROI	RJ
ESCO SAVING ENERGY	RUA DEMOSTHENES MADUREIRA DE PINHO, 895 - APT 301	RIO DE JANEIRO	RJ
ESCOLA DE GUERRA NAVAL	AVENIDA PASTEUR, 480 - 	RIO DE JANEIRO	RJ
ESPIRAL ANDAIMES E ESTRUTURAS TUBULARES	RUA VINTE E UM, S/N - LOTE 03 QUADRA 24B	DUQUE DE CAXIAS	RJ
ESTRUTURAL SERVIÇOS INDUSTRAIS LTDA	RUA PASSO DA PÁTRIA, 120 - SALA 707	DUQUE DE CAXIAS	RJ
EXIMPORT LUBEQUIP LTDA	RUA GENERAL ROBERTO ALVES DE CARVALHO FILHO, 37 - 	SÃO PAULO	SP
EZ - CRIOGENICS VENDAS E SERVICOS LTDA	RUA CORONEL MOREIRA CESAR, 400 - LOJA 100	RIO DE JANEIRO	RJ
FABRIMAR S A INDUSTRIA E COMERCIO	RODOVIA PRESIDENTE DUTRA, 1362 - 2290 E R B SILVA SN	RIO DE JANEIRO	RJ
FACULDADES CATOLICAS	RUA MARQUÊS DE SÃO VICENTE, 225, 225 - 	RIO DE JANEIRO	RJ
FATOR TOWERS OT CONSTRUCOES E INCORPORACOES LTDA	AVENIDA JOÃO CABRAL DE MELLO NETO, 400 - SAL 1502	Rio de Janeiro	RJ
FCA FIAT CHRYSLER AUTOMOVEIS BRASIL LTDA	AVENIDA CONTORNO, 3455 - 	BETIM	MG
FEY	AVENIDA PARIS, 280 - 	ARUJA	SP
FIRENG ENGENHARIA	RUA ITAGIBA, 110 - GALPAO08 LT JD B HORIZONTE QUADRA05 LOTE 04	LAURO DE FREITAS	BA
FIRENG ENGENHARIA	ESTRADA RJ 14, 52 - 	MANGARATIBA	RJ
FM2C SERVICOS DE MANUTENCAO LTDA	AVENIDA CARLOS GRIMALDI, 1701, 1701 - CONJ 01 B	CAMPINAS	SP
FMAUAD EMPREENDIMENTOS PARTICIPAÇÕES E ADM LTDA	RUA DIOGO JOSÉ PONCIANO, 879 - 	TERESÓPOLIS	RJ
FMC TECHNOLOGIES DO BRASIL LTDA	AVENIDA CORONEL PHIDIAS TÁVORA, 231 - 	RIO DE JANEIRO	RJ
FORCA 1 - LOCACOES	EST SAO GONCALO, 00372 - LOT 14 PAL 45995	RIO DE JANEIRO	RJ
FORCA 1 LOCACAO DE MAQUINAS E	,  - 		
FORSHIP ENGENHARIA SA	RUA URUGUAIANA, 94 - PAV 10	RIO DE JANEIRO	RJ
FRIGOEDEN ARMAZENS GERAIS E LOGISTICA LTDA	RUA MARIA GONZAGA, 460 - AREA	SÃO JOÃO DE MERITI	RJ
FUNDACAO BRASILEIRA DE TECNOLOGIA DA SOLDAGEM / FBTS	RUA HADDOCK LOBO, 369 - SALA 908	RIO DE JANEIRO	RJ
FUNDAÇÃO COORD.DE PROJETOS,PESQUISA E ESTUDOS TECNOLOGICOS	AVENIDA MONIZ ARAGÃO - BLOCO 1, 360 - CENTRO DE TECNOLOGIA - EXPANSÃO DO CGTEC CT2	RIO DE JANEIRO	RJ
FURNAS CENTRAIS ELÉTRICAS SA	QN 214, ÁREA ESPECIAL, 01 - S/N	BRASILIA	DF
FURNAS CENTRAIS ELETRICAS SA - JACAREPAGUA	ESTRADA PAU DA FOME,  - 	RIO DE JANEIRO	RJ
GAMBOA REFORMAS MARITIMAS LTDA	RODOVIA PROCURADOR HAROLDO FERNANDES DUARTE, S/N - KM 489,5	ANGRA DOS REIS	RJ
GARANTIA TOTAL REFORMADORA DE PNEUS LTDA	AVENIDA BRASIL, 28150 - 	RIO DE JANEIRO	RJ
GARRA GERADORES COMERCIAL SERVICOS E LOCACOES LTDA	RUA OLEGÁRIO MARIANO, 43 - 	DUQUE DE CAXIAS	RJ
GELMUNCK	TRAVESSA PEREIRA PASSOS, 6 - 	DUQUE DE CAXIAS	RJ
GERAR SERVIÇOS DE ENGENHARIA	PRAIA BOTAFOGO, 440, 440 - SALA 1301	RIO DE JANEIRO	RJ
GIGAMAX TRANSPORTES E SERVIÇOS LTDA	RUA JOSÉ DE ALENCAR, 74 - 	FEIRA DE SANTANA	BA
GLAXOSMITHKLINE BRASIL LTDA	ESTRADA DOS BANDEIRANTES, 8464 - 	RIO DE JANEIRO	RJ
GLOBO COMUNICACAO E PARTICIPACOES S/A	ESTRADA DOS BANDEIRANTES, 6.700 - 	RIO DE JANEIRO	RJ
GLOG TRANSPORTES LTDA	RUA DO ARROZ, 90 - SALA 567	RIO DE JANEIRO	RJ
GMAR SOLUCOES AMBIENTAIS LTDA	RUA CAPITÃO JOSÉ ANTÔNIO LAGAREIRO, 520 - 	MAUÁ	SP
GOMES ENGENHARIA	RUA PARANAGUA, 23 - 	RIO DE JANEIRO	RJ
GRATT INDUSTRIA DE MAQUINAS LTDA	R ANTONIO PELEGRINI, 45 - SALA 1, JARDIM DA SERRA	CAPINZAL	SC
GREEN4T SOLUCOES TI LTDA	RUA ALMIRANTE BALTAZAR, 333 - LOJA A	RIO DE JANEIRO	RJ
GREEN4T SOLUÇÕES TI S.A	AVENIDA GUPÊ, 10767 - GALPÃO 03	BARUERI	SP
GROUP TS LOGG LTDA	RUA SEBASTIÃO RAMOS, 150 - 	SÃO CARLOS	SP
GT MINAS TRANSPORTES E DISTRIBUIDORA LTDA	RUA CARLOS SEIDL, 910 - 	RIO DE JANEIRO	RJ
GT3 COMERCIO DE PNEUS LTDA	AVENIDA BRASIL, 28088 - 	RIO DE JANEIRO	RJ
GUAPI PAPEIS INDUSTRIA DE PAPEL E PAPELAO S/A	RODOVIA RIO-FRIBURGO, 429 - LOTE: 4 QUADRA: 23	GUAPIMIRIM	RJ
H MENESES TRANSPORTE,REMOCAO E ICAMENTO LTDA	RUA ARMANDINA, 139 - 	MESQUITA	RJ
HANSA-FLEX DO BRASIL LTDA	AVENIDA PARIS, 467 - 	RIO DE JANEIRO	RJ
HEAVY LIFT LOGISTICA LTDA	AVENIDA VINTE E SEIS DE MARÇO, 302 - SLJ	Poá	SP
HEBERT ENGENHARIA EIRELI	AVENIDA BARÃO DO RIO BRANCO, 3053 - SALA 1601	JUIZ DE FORA	MG
HEBERT ENGENHARIA LTDA	RODOVIA WASHINGTON LUIZ, 2550 - BL 02 SL.1102	Duque de Caxias	RJ
HEMORIO	RUA FREI CANECA, 59 - 	Rio de Janeiro	RJ
HIDROTANK RESERVATORIOS LTDA	ESTRADA MUNICIPAL STELIO MACHADO LOUREIRO, SN - FNP 040 KM 2,0	FERNANDO PRESTES	SP
HOSPITAL PLACI NITEROI	RUA MARTINS TORRES, 98 - 	NITERÓI	RJ
HOTWORK BRASIL	ESTRADA PREFEITO WILSON PEDRO FRANCISCO, 663 - QUADRA0046 LOTE 0038	ITAGUAI	RJ
HOWDEN	AVENIDA OSVALDO BERTO, 475 - DISTRITO IND. ALFREDO RELA	ITATIBA	SP
HYDRA ENGENHARIA E SANEAMENTO LTDA	AVENIDA DAS AMÉRICAS, 3434 - BLC 2 SAL 205	RIO DE JANEIRO	RJ
ICAR SOLUCOES EM ICAMENTOS EIRELI	AVENIDA PRESIDENTE JUSCELINO KUBITSCHECK, 10839 - 	JUIZ DE FORA	MG
ICONIC LUBRIFICANTES S.A.	R SILESIA, 3501 - PARTE	DUQUE DE CAXIAS	RJ
ICONIC LUBRIFICANTES S.A.	R MONSENHOR MANOEL GOMES, 00140 - 	RIO DE JANEIRO	RJ
ICTSI RIO BRASIL TERMINAL 1 S.A.	RUA MONSENHOR MANUEL GOMES, S/N - TERMINAL CONTAINERS I	RIO DE JANEIRO	RJ
IGREJA DE NOVA VIDA DE MARICA	RUA ALFERES GOMES LOTE 17 QD 81A,  - 	MARICÁ	RJ
INDUSTRIA DE TRANSFORMADORES ITAIPU LTDA	AVENIDA SERGIO ABDUL NOUR, 2106 - 	ITÁPOLIS	SP
INDUSTRIAS NUCLEARES DO BRASIL S/A - INB	ROD PRESIDENTE DUTRA, SN - KM 330	RESENDE	RJ
INSTITUTO DE PESQUISA JARDIM BOTANICO DO RIO DE JANEIRO	RUA PACHECO LEÃO, 915 - PORTAO DE TRAS	RIO DE JANEIRO	RJ
INSTITUTO DE TECNOLOGIA EM FARMACOS	AV COMANDANTE GUARANYS, 447 - 	RIO DE JANEIRO	RJ
INSTITUTO DE TECNOLOGIA EM IMUNOBIOLOGICOS	AV BRASIL, 4365 - 	RIO DE JANEIRO	RJ
INSTITUTO MILITAR DE ENGENHARIA	PRAÇA GENERAL TIBURCIO, 80 - 	RIO DE JANEIRO	RJ
INSTITUTO NACIONAL DE CARDIOLOGIA	RUA DAS LARANJEIRAS, 374 - 2° ANDAR	RIO DE JANEIRO	RJ
INSTITUTO NACIONAL DO CANCER	PRAÇA CRUZ VERMELHA, 23 - 	RIO DE JANEIRO	RJ
INTECH CONSTRUÇÃO E MONTA	AVENIDA ADOLFO PINHEIRO, 1010 - CONJUNTO 52	SAO PAULO	SP
INTERSERVICE SERVIÇOS OFFSHORE LTDA	RUA LADY ESTEVES DA CONCEIÇÃO, 680 - 	MACAÉ	RJ
ITS INFORMOV	RUA SANTA JUSTINA, 660 - CONJ 101 102 103 E 104	SAO PAULO	SP
JBK SERVICO E CONSTRUCAO CIVIL LTDA	RUA DOIS (LOT ARGEU FAZENDINHA), S/N - QUADRA98 LOTE 04	NITEROI	RJ
JCT MANUTENCAO INDUSTRIAL E COMERCIAL LTDA	RUA SÃO CIRO, 25 - LOTE 34 PAL 22103 QUADRA 22	RIO DE JANEIRO	RJ
JCTM COMERCIO E TECNOLOGIA AMBIENTAL	R ROBERTO ROCHA, 417 - 	BELFORD ROXO	RJ
JELNIT ENGENHARIA E FACILITIES LTDA	TRAVESSA MÁRIO NEVES, 75 - 	NITERÓI	RJ
JEMP MONTAGENS E DESMONTAGENS INDUSTRIAIS LTDA	RUA ANITA MARIA BOTTI PEDROSO, 358 - 	CABREÚVA	SP
JOTA ELE - KIIR	RUA DA AJUDA, 5 - 	RIO DE JANEIRO	RJ
JSL SA	RUA MANOEL PINHEIRO, SN - 	MANGARATIBA	RJ
K&M SERVICOS DE MANUTENCAO EIRELI	RUA DE SANTANA, 143 - SOBRELOJA 201	RIO DE JANEIRO	RJ
KARPOWERSHIP BRASIL ENERGIA LTDA	RUA LAURO MULLER, 116 - SALA 3302	RIO DE JANEIRO	RJ
KLACON EDIFICAÇÕES LTDA	RUA VISCONDE DE PIRAJÁ, 330 - SALA 112	RIO DE JANEIRO	RJ
KURT SOL AR CONDICIONADO LTDA	RUA GUAIAÚNA, 235 - PENHA	SÃO PAULO	SP
KWAY SOLUCOES INTEGRADAS	ROD GOVERNADOR MARIO COVAS - KM 281, GLEBA 01, SN - GALPAO01 PAVMTO01 BLOCO 01 SALA 125	CARIACICA	ES
L.C.D. ENGENHARIA, CONSTRUCOES, MONTAGENS E MANUTENCOES INDUSTRIAIS LTDA	AV RIO BRANCO, 00185 - SAL 1220	RIO DE JANEIRO	RJ
LABONE	RUA PROFESSOR JOSE ASSAD ATALLA JUNIOR, 183 - SALA 2	BOITUVA	SP
LABORATORIO FARMACEUTICO DA MARINHA	AVENIDA DOM HÉLDER CÂMARA, 315 - 	RIO DE JANEIRO	RJ
LANLIMP DESCARTAVEIS E LIMPEZA LTDA	RUA MINAS GERAIS, 1300 - GALPAO BCAMPO ALEGRE	QUEIMADOS	RJ
LAYNE DO BRASIL	RUA RICARDO MACHADO, 69 - 	RIO DE JANEIRO	RJ
LESTE ENGENHARIA E SERVICOS TECNICOS LTDA	PRAÇA OLAVO BILAC, 28 - SL 1107	RIO DE JANEIRO	RJ
LIGHT SERVIÇOS DE ELETRICIDADE S/A	AVENIDA MARECHAL FLORIANO, 168 - 	RIO DE JANEIRO	RJ
LINHA VIVA TRANSPORTES	RUA SARGENTO AQUINO, 353 - 	RIO DE JANEIRO	RJ
LMENDES ADMINISTRACAO DE BENS LTDA	RUA CONDE DE BONFIM, 163 - APT 203	RIO DE JANEIRO	RJ
LOCAR GUINDASTES E TRANSPORTES INTERMODAIS S A	AVENIDA BRASIL, 15295 - 	Rio de Janeiro	RJ
LOGISTICA E ARMAZENAGENS GERAIS FRIGOEDEN LTDA	RUA MARIA GONZAGA, 460 - 	SÃO JOÃO DE MERITI	RJ
LSI - LOGISTICA S.A.	AVENIDA ATLÂNTICA, 386 - SALA 109	MACAÉ	RJ
LUCCA YALLOUZ DE CARVALHO	AVENIDA MARIA LUIZA,, 1395 - 	Engenheiro Paulo de Frontin	RJ
LUCIA HELENA NEVES ALEXANDRINO SANTOS ME	RUA ITAPARANTIM, 698 - 	GUARULHOS	SP
LV CASTRO ENGENHARIA E INSPECAO INDUSTRIAL EIRELI	RUA DOUTOR GERINO DE SOUZA FILHO, 274 - COND EMPRES LT NORTE	LAURO DE FREITAS	BA
MADEIRAS E FERRAGENS ZONA OESTE COMERCIO VAREJISTA LTDA.	EST DA PEDRA, 00396 - A	RIO DE JANEIRO	RJ
MAMMA JAMMA RECREIO | MJP RECREIO RESTAURANTE LTDA	AVENIDA DAS AMERICAS, 19021 - LOJ 103	RIO DE JANEIRO	RJ
MANSERV FACILITIES LTDA	RUA PAULO EMIDIO BARBOSA,, S/N - ANDAR 1 QUADRA 1 ILHA DO FUNDAO	RIO DE JANEIRO	RJ
MARCASA EMPREENDIMENTO IMOBILIÁRIO LTDA.	AVENIDA CONSELHEIRO NÉBIAS, 756 - 	Santos	SP
MARCILENE SILVINO DA COSTA	RUA MENA BARRETO, 151 - 	RIO DE JANEIRO	RJ
MARFRA TRANSPORTE E LOGISTICA LTDA	AVENIDA VENEZUELA, 3 - ANDAR 5 SALAS 511/512/513	RIO DE JANEIRO	RJ
MARIA ISABEL FERRAZ MAGALHAES	RODOVIA PROCURADOR HAROLDO FERNANDES DUARTES, 18 - KM 475	ANGRA DOS REIS	RJ
MARINA DO PIRATAS SPE S/A	ESTRADA MUNICIPAL, 200 - HANGARES 1,2,3	ANGRA DOS REIS	RJ
MARINA VEROLME S /A	AV WINS TON MARUCA, S/N - 	ANGRA DOS REIS	RJ
MARKO SISTEMAS METALICOS	AVENIDA MARECHAL HENRIQUE LOTT, 163 - BLOCO 2 SALA 303 NIVEL SUP AV AMERICAS 3693	RIO DE JANEIRO	RJ
MARKO SISTEMAS METALICOS DE CONSTRUCAO LTDA	R CINCO, S/N - LOTE 02,03,04,20,21 E 22 QUADRA B	ITAGUAI	RJ
MARTE ENGENHARIA LTDA	RUA DA QUITANDA,, 86 - SALA 202/203	RIO DE JANEIRO	RJ
MAVIKI EQUIPAMENTOS INDUSTRIAIS LTDA	RODOVIA WASHINGTON LUIZ, 19986 -  MAVIKI EQUIPAMENTOS INDUSTRIAIS LTDA RODOVIA WASH	DUQUE DE CAXIAS	RJ
MAXPESA	AVENIDA CASSIANO RICARDO, 601 - SALA 61 E 63	SAO JOSE DOS CAMPOS	SP
MAXPESA CONSTRUCOES	RUA DESEMBARGADOR MARIO DA SILVA NUNES, 120 - EDIF ENSEADA DA BAIA SALA 201	VITORIA	ES
MAXPESA CONTRUCOES TRANSPORTES LOCACOES E MONTAGENS LTDA	AVENIDA PERIMETRAL EMÍLIO DE MENEZES, SN - Q11 L 10	DUQUE DE CAXIAS	RJ
MEGA BOR COMERCIO DE EQUIPAMENTOS E VESTUARIO EIRELI	RUA FIGUEIRA DE MELO, 260 - 	RIO DE JANEIRO	RJ
MEGA ENGENHARIA & SOLUÇÕES EIRELI - ME	RUA ANANIAS F DE CARVALHO, SN - QD22, LT12.	NIQUELÂNDIA	GO
MEGALIFT LOCACAO E TRANSPORTES INTERMODAIS LTDA.	AVENIDA MAJOR SYLVIO DE MAGALHÃES PADILHA, 5200 - 5 ANDAR - BLOCO E CONJ 509	SÃO PAULO	SP
MEGATRANZ TRANSPORTES LTDA	AVENIDA NARAIN SINGH, 1200 - 	GUARULHOS	SP
MESSER GASES LTDA	AVENIDA BRASIL, 20491 - 	RIO DE JANEIRO	RJ
METAL ALFA LTDA	ESTRADA ADILIA BARBOSA NEVES, 2215 - 	ARUJA	SP
METALÚRGICA BALENA LTDA	RUA TERESA ALVES, 166 - 	Ponta Grossa	PR
MIDAS ENGENHARIA LTDA	RUA FRANCO ZAMPARI, 239 - 	RIO DE JANEIRO	RJ
MILLS LOCACAO, SERVICOS E LOGISTICA S.A.	EST DO GUERENGUE, 1381 - PARTE	RIO DE JANEIRO	RJ
MLX COMERCIO DE GASES LTDA	RODOVIA GOVERNADOR MÁRIO COVAS, SN - BR 101 - 79.851.647	ITABORAÍ	RJ
MODEC SERVICOS DE PETROLEO DO BRASIL LTDA	AVENIDA PREFEITO ARISTEU FERREIRA DA SILVA, 2500 - 	MACAÉ	RJ
MOGITRAFO INSDUSTRIA E COMERCIO DE TRANSFORMADORES	RUA SEBASTIÃO EUZÉBIO DE OLIVEIRA, 498 - 	MOGI MIRIM	SP
MOINHO IPIRANGA	AVENIDA DOUTOR ULYSSES GUIMARAES, 4105 - 	DIADEMA	SP
MONGEL -VENDAS, REPAROS E LOCACAO DE GUINDASTES LTDA	AVENIDA DAS PRIMAVERAS, 615 - SALAS 01 E 02	TARUMÃ	SP
MONTRAFO SERVIÇOS EM TRANSFORMADORES EIRELI	RUA MINERVINO DE OLIVEIRA E SOUZA, 400 - 	PIRAQUARA	PR
MPE ENGENHARIA E SERVIÇOS SA	RUA SÃO FRANCISCO XAVIER, 603 - 	RIO DE JANEIRO	RJ
MRO SERVICOS LOGISTICA S A	AV DAS AMERICAS, 700 - BLOCO 5 CONJ 101B E 102B	RIO DE JANEIRO	RJ
MULTIWAY	ESVC JULIO DUARTE, 369 - 	AGUAI	SP
MV CONSTRUCOES	RUA ERNANI DE PAIVA, 00141 - 	RIO DE JANEIRO	RJ
NAIARA FLAVIA FERREIRA ALVES NEVES	RUA FLOR-DE-JAMBO, 26 - 	Belo Horizonte	MG
NBC SISTEMAS DE ENERGIA LTDA	RUA ACIAS, 48 - PARTE	RIO DE JANEIRO	RJ
NCX TRANSPORTES E SERVICOS DE LOGISTICA LTDA	AVENIDA JOAQUIM LEITE, 01 - SALA 202	BARRA MANSA	RJ
NEOFACILITIES MANUTENCAO PREDIAL LTDA	RUA PROJETADA 11 CV, 75 - 	DOURADOS	MS
NHJ DO BRASIL	AVENIDA BRASIL, 4880 - GALPAO RUA ONZE 95 GALPAO RUA 8 680 700 E 710 RUA	RIO DE JANEIRO	RJ
NIPLAN - MID INFRAESTRUTURA S.A.	AV ALFREDO EGIDIO DE SOUZA ARANHA, 75 - CONJ 51	SAO PAULO	SP
NIPLAN ENGENHARIA S.A.	RUA DEPUTADO MARTINHO RODRIGUES, 51 - 	SÃO PAULO	SP
NM-ENGENHARIA LTDA	RUA ALCINDO GUANABARA, 24 - SALAS 1712 E 1713	Rio de Janeiro	RJ
NORSIL QUIMICA E INDUSTRIA LTDA	EST RJ - 127, S/N - LOTE 16	PARACAMBI	RJ
NORSIL QUIMICA E INDUSTRIA LTDA	R LOREN FRANCISCO SILVA, 36 - LOTE 06 QUADRA 04	PINHEIRAL	RJ
NOVA TRANSPORTADORA DO SUDESTE S/A - NTS	RUA ELISA MARIA, S/N - 	Duque de Caxias	RJ
NOVA TRANSPORTADORA DO SUDESTE S/A - NTS (FILIAL TAUBATÉ)	AVENIDA ROBERTO BERTOLETTI, 1211 - 	Taubaté	SP
NOVA TRANSPORTADORA DO SUDESTE S/A - NTS ARAPEI	RURAL JOSE CARVALHO DE FARIA,, SN - KM 10 - PARTE	Arapeí	SP
NOVA TRANSPORTADORA DO SUDESTE S/A - NTS JAPERI	ESTRADA DOS EUCALIPTOS, SN - 	JAPERI	RJ
NOVA TRANSPORTADORA DO SUDESTE S/A TAUBATÉ	ESTRADA DO BARREIRO, 8391 - KM 06 - PARTE	Taubaté	SP
NOVO HORIZONTE JACAREPAGUA IMPORTAÇÃO E EXPORTAÇÃO S/A.	AVENIDA ZEN, SN - LOTE 1 2 A E 2 B	RIO DAS OSTRAS	RJ
NUMPEX-BIO - NÚCLEO MULTIDISCIPLINAR DE PESQUISA EM BIOLOGIA UFRJ	ESTRADA DE FERRO XEREM, 27 - 	DUQUE DE CAXIAS	RJ
NURRA ENGENHARIA LTDA	ALAMEDA PIO XI, 01 - 	ARRAIAL DO CABO	RJ
OCEANPACT SERVICOS MARITIMOS S.A.	RUA DA GLÓRIA,  - SALAS 801 E 802 10PAVIMENTO SALAS 901 E 902 11 PAV	RIO DE JANEIRO	RJ
OECI S.A	AVENIDA CIDADE LIMA, 86 - 	RIO DE JANEIRO	RJ
OGGI SORVETES LTDA	RUA EUSTAQUIO AZEVEDO, QD 17 - LOTE 18	DUQUE DE CAXIAS	RJ
OPPORTUNITY	ST SETOR CENTRAL Q 28 CJ A LT 6, S/N - SALA 201	BRASILIA	DF
ORIENTE CONSTRUÇÃO	EST ARARUAMA RIO BONITO, S/N - RODOVIA RJ 124 KM 33	ARARUAMA	RJ
ORIZON VALORIZACAO DE RESIDUOS S.A	AVENIDA DAS NAÇÕES UNIDAS, 12901, 12901 - 8º ANDAR	SÃO PAULO	SP
PADO S/A INDUSTRIAL COMERCIAL E IMPORTADORA	RUA DO SOL, 84 - 	CAMBÉ	PR
PAS PEÇAS E SERVIÇOS LTDA	RUA SERAFIM, SN -  LOTE:25 E 26;QUADRA:13	DUQUE DE CAXIAS	RJ
PASHAL	AVENIDA SARGENTO DA AERONAUTICA JAIME R. PEREIRA, 652 - GALPAOA	GUARULHOS	SP
PAURA PROJETOS SERVICOS E MONTAGEM LTDA	ESTRADA DO GUERENGUE, 299 - LOJA D	RIO DE JANEIRO	RJ
PAX INVESTIMENTOS EM AEROPORTOS S.A	AVENIDA PRESIDENTE JUSCELINO KUBITSCHEK, 1909, 1909 - CONJ 301	SÃO PAULO	SP
PB SOLUÇOES DE ENGENHARIA	RUA PAULINO AFONSO, 477 - 	PETRÓPOLIS	RJ
PEDREIRA JAPERI	EST ARY SCHIAVO, S/N - KM 1 50 PEDREIRA CHACRINHA	JAPERI	RJ
PENSALAB EQUIPAMENTOS INDUSTRIAIS S.A.	R MINERVA, 129 - 	SAO PAULO	SP
PETROBRAS TRANSPORTE S/A TRANSPETRO	ILHA DA AGUA, SN - 	RIO DE JANEIRO	RJ
PETROBRAS TRANSPORTE S/A TRANSPETRO	AVENIDA ANTÔNIO BERTHOLDO DA SILVA JORDÃO, 8441 - 	Angra dos Reis	RJ
PETROLEO BRASILEIRO S A	ROD ALCA LESTE, SN - 	IBIRITÉ	MG
PETROLEO BRASILEIRO S A PETROBRAS	ROD WASHINGTON LUIZ BR 040, SN - KM 113 7	DUQUE DE CAXIAS	RJ
PETROLEO BRASILEIRO S.A. - PETROBRAS	RODOVIA BR-101, S/N - KM 164 - PARTE	MACAE	RJ
PETROLEO BRASILEIRO S/A PETROBRAS	RUA FRANCISCO DE SOUSA E MELO, 1590 - 	RIO DE JANEIRO	RJ
PETROLEO BRASILEIRO S/A PETROBRAS	ROD AMARAL PEIXOTO, 11000 - KM 177	MACAE	RJ
PETROLEO BRASILEIRO S/A PETROBRAS	AVENIDA ELIAS AGOSTINHO, 665 - PARTE	MACAÉ	RJ
PETROLEO BRASILEIRO SA	RUA DOUTOR JOÃO PERESTRELO, 185 - PARTE	DUQUE DE CAXIAS	RJ
PETROLEO BRASILEIRO SA	RUA FRANCISCO DE SOUSA E MELO, 1580 - 1590	RIO DE JANEIRO	RJ
PHELIPE TRANSPORTES RODO AEREO LTDA	RUA JOAQUIM OLIVEIRA FREITAS, 627 - 	SÃO PAULO	SP
PIPEWAVE MONTAGENS E PROJETOS DE ENGENHARIA LTDA	AVENIDA DE SANTA CRUZ, 10280 - 	RIO DE JANEIRO	RJ
PLAMONT - PLANEJAMENTO MONTAGEM E ENGENHARIA LTDA	RODOVIA RIO-SANTOS, SN - LOTE 09 E 12 QUADRA14	ITAGUAÍ	RJ
PLANO B TRANSPORTES LTDA	R DA FARINHA, 1075 - LOTE 15 PAL 23868 QUADRABM - PARTE	RIO DE JANEIRO	RJ
PLANOVA PLANEJAMENTO E CONSTRUCOES S.A.	RUA CAMPOS SALES, 226 - 	BARUERI	SP
PLAY CITY DIVERSOES LTDA	AVENIDA PASTOR MARTIN LUTHER KING JR, 126 - BLC 9 SAL 418 TOR 3	RIO DE JANEIRO	RJ
PLENA LOGISTICA LTDA.	RODOVIA WASHINGTON LUIZ, 1951 - 	DUQUE DE CAXIAS	RJ
PMH  PRODUTOS MÉDICOS HOSPITALARES LTDA	SIA TRECHO 17 RUA 08, 170 - 	BRASÍLIA	DF
POLLO ENGENHARIA EIRELI	RUA LIMOEIRO,  - RUA C- QD E -LOTE 3	CAMAÇARI	BA
PORTO DO ACU OPERACOES S.A	FAZENDA SACO DANTAS, 804 - 5 DISTRITO	SAO JOAO DA BARRA	RJ
PRAMAR CARIOCA COMERCIO E INDUSTRIA LTDA	AVENIDA DEMÉTRIO RIBEIRO, SN - QD 08 LOTES 15/16/17	DUQUE DE CAXIAS	RJ
PREMAG	RODOVIA SANTOS DUMONT, 49 - BR 116 KM 111 5	MAGE	RJ
PREMOVALE PROJETOS E CONSTRUCOES LTDA	ESTRADA NOSSA SENHORA APARECIDA, 1991 - 	CAÇAPAVA	SP
PRIMETALS TECHNOLOGIES BRAZIL LTDA.	R CAMPO LIMPO, 00100 - 	RIO DE JANEIRO	RJ
PROBITEC - PRODUTOS BETUMINOSOS E TECNOLOGIA DE APLICAÇÃO S/A	AVENIDA CANAL DA PAVUNA, 620 - 	Rio de Janeiro	RJ
PRODUTOS ROCHE QUÍMICOS E FARMACÊUTICOS S.A	ESTRADA DOS BANDEIRANTES, 2020 - 	Rio de Janeiro	RJ
PROFMONT CALDEIRARIA LTDA	RUA MARIANA, 87 - SALA 202	IPATINGA	MG
PROGEN PROJETOS GERENCIAMENTO E ENGENHARIA S.A	AVENIDA NILO PEÇANHA, 2516 - EDIFICIO RODOLPHO DE PAOLI	RIO DE JANEIRO	RJ
PROGT INDUSTRIAL LTDA	RUA 1, 235 - 	PAULÍNIA	SP
PSD SOLUTIONS ENGENHARIA,	R SAO CRISTOVAO, 00587 - SBR	RIO DE JANEIRO	RJ
QUALITY 3 MANUTENCAO HIDRAULICA LTDA	AVENIDA GETÚLIO DE MOURA, 560 - 	MESQUITA	RJ
QUANTUN QUIMICA LTDA	AVENIDA GOVERNADOR LEONEL DE MOURA BRIZOLA, S/N - QUADRA03 LOTE 28 LOTE 29	DUQUE DE CAXIAS	RJ
QUILOMBO ENERGIA S A	PRAÇA SAO JOSE, SN - 	CARMO	RJ
R. O. ALVES TRANSPORTES	AVENIDA CARMELINA ALVES DOS SANTOS, 16310 - 	SÃO JOSÉ DOS CAMPOS	SP
R.A LOCAÇÕES LTDA	RUA PETRINA GOMES MACHADO, 134 - 	LEOPOLDINA	MG
RAFT EMBALAGENS LTDA	RUA MINAS GERAIS, 10 - 9C 37 VB QD 03	QUEIMADOS	RJ
RAVI ENGENHARIA	PRACA ISAI LEIRNER, 135 - SALA 01	SAO PAULO	SP
RC CONSTRUCAO E MONTAGEM LTDA	AVENIDA DO LARANJAL, S/N - QUADRA16 B LOTE 10	DUQUE DE CAXIAS	RJ
REFRAMAX ENGENHARIA LTDA	RUA BERNARDO FIGUEIREDO, 33 - PAVMTO3 MZNINO	BELO HORIZONTE	MG
RETUBAR SERVICOS INDUSTRIAIS LTDA	ESTRADA KINOSHITA, 303 - 	COTIA	SP
REVESTMAN - REVESTIMENTOS E MANUTENCAO INDUSTRIAL LTDA	AVENIDA GUIMARAES ROSA, 400 - 	Três Marias	MG
RHITEC MONTAGEM INDUSTRIAL	AVENIDA MOGI GUACU, 700 - APT 34 BLOCO J ANDAR 2	SANTA BARBARA D OESTE	SP
RIBEIRÃO LOGÍSTICA E TRANSPORTES LTDA	RUA NABUCO DE FREITAS, 56 - 	RIO DE JANEIRO	RJ
RIO REPAROS	RUA LADISLAU NETO, 00079 - APT 101	RIO DE JANEIRO	RJ
RIO SUL CONSTRUCOES	RUA ABREU CESAR, 05 - 	VASSOURAS	RJ
RIOPET EMBALAGENS S.A.	RUA PROFESSOR EDUARDO VIANNA, 175 - GALPAO I	NOVA IGUACU	RJ
RIP SERVICOS INDUSTRIAIS LTDA	AVENIDA PREFEITO ARISTEU FERREIRA DA SILVA, 2133 - 	MACAÉ	RJ
RIP SERVIÇOS INDUSTRIAIS LTDA	AVENIDA CANAL MD ETR JOAO XXIII, 1 - RUA 3 LJ 1-QD A LT 6	RIO DE JANEIRO	RJ
RMT TRANSPORTES	RUA ALTO PORA, 216 - 	RIO DE JANEIRO	RJ
ROCCA EVENTOS LTDA	RUA MATO GROSSO, 497 - SALA 05 ANDAR 01	CURITIBA	PR
RODENSTOCK BRASIL INDUSTRIA OPTICA LTDA	ESTRADA DOS BANDEIRANTES, 2871 - 	RIO DE JANEIRO	RJ
RODOVIARIA DO RIO	AVENIDA FELICIANO SODRE, S/N - TERMINAL RODOVIARIO ROBERTO SILVEIRA	NITEROI	RJ
RODOVIARIA DO RIO DE JANEIRO S/A	AVENIDA FRANCISCO BICALHO, 1 - 	RIO DE JANEIRO	RJ
RODOVIÁRIO NOVA ERA LTDA	AVENIDA BOQUEIRÃO,  - 	CANOAS	RS
RUNTIME AUTOMATION SOLUCOES INDUSTRIAIS LTDA	AVENIDA HOMERO LEITE, 206 - SALA 201	BARRA MANSA	RJ
SADI TRANSPORTES EIRELI	AVENIDA LUIZ PASTEUR, 1723 - 	ESTEIO	RS
SALMERON ENERGIA RENOVAVEL E PROTEÇÃO AO CLIMA RIO LTDA	RODOVIA SANTOS DUMONT, S/N - GALPÃO 01 LT D	GUAPIMIRIM	RJ
SANDENE S.A. INDUSTRIA E COMERCIO	AVENIDA ANTÔNIO CABRAL DE SOUZA, 4301 - ANEXO |	PAULISTA	PE
SAPURA	PRAIA BOTAFOGO, 186 - 7 ANDAR TORRE OSCAR NIEMEYER	RIO DE JANEIRO	RJ
SATHEL ENERGIA S/A EQUIPAMENTOS E SERVICOS	AVENIDA MARGINAL, 223 - 	COTIA	SP
SCP UFV SELVA	AVENIDA DAS AMÉRICAS, 4200, BL 1 - SALA 305	RIO DE JANEIRO	RJ
SE MAGÉ	AVENIDA SIMÃO DA MOTA,  - BR 116 KM 113	MAGÉ	RJ
SEEPIL VALVULAS E EQUIPAMENTOS LTDA	ESTRADA FAZENDINHA DO RECREIO, SN - LOTE 19 QUADRA01 PARTE	DUQUE DE CAXIAS	RJ
SELL SERVIÇOS ESPECIAIS DE ENGENHARIA LTDA	AVENIDA PRESIDENTE VARGAS, 583 - SL1701	Rio de Janeiro	RJ
SEPETIBA TECON S/A	ESTRADA PREFEITO WILSON PEDRO FRANCISCO, SN - 	ITAGUAÍ	RJ
SEPLAN SERVICE BUSINESS	RUA DO IPIRANGA, 148 - 	CAMPOS DOS GOYTACAZES	RJ
SERTEMIL ENGENHARIA COMERCIO E LOCACAO DE GUINDASTES LTDA	AVENIDA ANTÔNIO WALDIR MARTINELLI, 2430 - 	SERTÃOZINHO	SP
SERVICO NACIONAL DE APRENDIZAGEM COMERCIAL - SENAC ARRJ	RUA MARQUÊS DE ABRANTES, 99 - 	RIO DE JANEIRO	RJ
SERVICO NACIONAL DE APRENDIZAGEM INDUSTRIAL SENAI	RUA SENHOR DO BONFIM, 130 - 	BARRA MANSA	RJ
SERVICO SOCIAL DO COMERCIO - SESC ADMINISTRACAO REGIONAL DO RIO DE JAN	RUA MARQUÊS DE ABRANTES, 99 - 	RIO DE JANEIRO	RJ
SERVI-SÁ AUTO GUINDASTE LOCAÇÃO LTDA	RODOVIA PRESIDENTE DUTRA, 108 - KM 269	BARRA MANSA	RJ
SEST SENAT DUQUE DE CAXIAS	ESTRADA DO BOITATA, S/N - 	DUQUE DE CAXIAS	RJ
SETMAR	RUA JOAO TORQUATO, 00268 - FDS	RIO DE JANEIRO	RJ
SHEMAR LATAM HOLDING LTDA	PRAIA BOTAFOGO, 501 - SALA 129	RIO DE JANEIRO	RJ
SILIMED - INDUSTRIA DE IMPLANTES LTDA	ROD WASHINGTON LUIZ, . - SITIO 20 AREA A SITIO 21 AREA B	DUQUE DE CAXIAS	RJ
SILIMED - INDUSTRIA DE IMPLANTES LTDA	R FIGUEIREDO ROCHA, 374 - 	RIO DE JANEIRO	RJ
SISTENGE CONSTRUÇÕES E COMÉRCIO LTDA	RUA OUVIDOR PELEJA, 111 - 9º ANDAR	SÃO PAULO	SP
SKYFIT	RUA SANTA BEATRIZ, 100 - CASA 01 QD. 07 LT. 33	MARICA	RJ
SLIM SOLUCOES	RUA RIO CLARO, 00364 - 	RIO DE JANEIRO	RJ
SLTK MANUTENCOES E LOCACAO LTDA	RUA CAROBINHA, 54 - LOTE 16QUADRA 83 PA	RIO DE JANEIRO	RJ
SM REPRESENTAÇÕES E COMÉRCIO DE MÁQUINAS LTDA	AVENIDA TALMA RODRIGUES RIBEIRO,  - 	SERRA	ES
SOLVI ESSENCIS AMBIENTAL S.A.	RODOVIA SANTOS DUMONT, SN - KM121 5	MAGÉ	RJ
SOTREQ S/A	AVENIDA BRASIL, S/N - KM 111,5	RIO DE JANEIRO	RJ
SOTREQ SA	AV MOTA COQUEIRO, S/N - QUADRA: C; LOTE: 2 E 3;	MACAE	RJ
SPE GOLF 2EMPREENDIMENTOS IMOBILIARIOS LTDA	AVENIDA DAS AMÉRICAS, 3.500 - 	RIO DE JANEIRO	RJ
SPRINT RENTAL LTDA EPP	AVENIDA DAS AMÉRICAS, 700 - BLOCO 6 SALA 126 E 127	RIO DE JANEIRO	RJ
SRA EQUIPAMENTOS E SISTEMAS LTDA	RUA ÍRIS ALVIM CAMARGOS, 7 - 	BELO HORIZONTE	MG
STEEL EQUIPAMENTO LOCACAO E SERVICO LTDA EPP	RUA OTRANTO, 956 - 	RIO DE JANEIRO	RJ
STME MANUTENCAO E MONTAGENS LTDA	AVENIDA DOUTOR GERALDO MENECUCCI DE OLIVEIRA, 51 - 	MACAÉ	RJ
STN EMPREENDIMENTOS E CONSTRUÇÕES LTDA	RUA JOSE SANTINON, 313 - 	AREAL	RJ
SUNO DISTRIBUIDORA SOLAR S.A.	AVENIDA JOÃO FRANCISCO GONÇALVES, 100 - SALA 05	VILA VELHA	ES
SUPERMERCADOS GUANABARA	R AURELIO DE FIGUEIREDO, 205 - 	RIO DE JANEIRO	RJ
SUPERMIX CONCRETO S/A	RUA CORONEL GONÇALVES, 260 - LETRA A	SÃO JOSÉ DOS CAMPOS	SP
TAG DEL SOL TRANSPORTES LTDA - ME	VIA ANHANGÜERA, 16.950 - KM 17	SÃO PAULO	SP
TEIXEIRA DUARTE - ENGENHARIA E CONSTRUCOES, S.A.	R DOMINGOS JANNUZZI, 119 - SALA 105	MANGARATIBA	RJ
TERMORIO JUIZ DE FORA	ESTRADA DO CARACOL, 595 - 	JUIZ DE FORA	MG
THORNER ENGENHARIA LTDA	RUA JOSÉ CARLOS LEITE, 69 - 	SÃO GONÇALO	RJ
THS TRANSPORTE E LOGISTICA LTDA	RUA SISA, 178 - CONJUNTO 1	GUARULHOS	SP
TJH SERVICOS E MONTAGEM INDUSTRIAL LTDA	RUA PASTEUR, 225 - QUADRA24 LOTE 1 F CASA III	DUQUE DE CAXIAS	RJ
TNF TRANSPORTES E GUINDASTES NORTE FLUMINENSE	RUA ALCIDES DA CONCEIÇÃO, 10 - 	MACAÉ	RJ
TOTAL CONSULTORIA , MANUTENCAO E MONTAGENS INDUSTRIAIS LTDA	AVENIDA PASTOR MARTIN LUTHER KING JR, 10771 - LOT 3 BENF PAL 5898 QDR 7	Rio de Janeiro	RJ
TRANSDALLA	RUA EMBAU, 02207 - LOT 1 PAL 45723	RIO DE JANEIRO	RJ
TRANSFORMADORES E SERVIÇOS DE ENERGIA DAS AMERICAS S.A	RODOVIA BR-381, 3045 - 	CONTAGEM	MG
TRANSFORMADORES E SERVICOS DE ENERGIA DAS AMERICAS S.A.	RODOVIA BR-262, SN - KM 364	BETIM	MG
TRANSFORMADORES UNIAO INDUSTRIA E COMERCIO LTDA	RUA FORTE DO RIO NEGRO, 220 - 	SÃO PAULO	SP
TRANSHIP TRANSPORTES MARITIMOS LTDA	RUA MANUEL DUARTE, 2291 - 	SÃO GONÇALO	RJ
TRANSMAQUINA	AVENIDA JUSCELINO KUBITSCHEK DE OLIVEIRA, 4123 - 	PATOS DE MINAS	MG
TRANSPES	VIA EXPRESSA, 15999 - 	BETIM	MG
TRANSPETRO	RODOVIA GOVERNADOPR MARIO COVAS, KM 471 - 	ANGRA DOS REIS	RJ
TRANSPI - TRANSPORTES PESADOS ITAJAI LTDA	RODOVIA BR-101, 10605 - KM 124	ITAJAÍ	SC
TRANSPORTADORA CRUZ DE MALTA LTDA	AVENIDA GUILHERME COTCHING, 346 - 	SÃO PAULO	SP
TRANSRIO CAMINHOES, ONIBUS, MAQUINAS E MOTORES LTDA	AVENIDA HENRY NESTLE, 3600 - 	CACAPAVA	SP
TRANZIRAN TRANSPORTES LTDA	RUA DO ALHO, 1129 - GALPÃO 2	RIO DE JANEIRO	RJ
TRIMAK ENGENHARIA E COMERCIO LTDA	ESTRADA CAETANO XAVIER DE MORAES, 720 - 	CAIEIRAS	SP
TRIMAK ENGENHARIA E COMERCIO LTDA	RUA ALFREDO VIEIRA ALVES, 180 - 	CAMPINAS	SP
TRIMAK ENGENHARIA E COMÉRCIO S/A	AVENIDA PORTUGAL, 4756 - 	BELO HORIZONTE	MG
TRIMAK ENGENHARIA E COMERCIO S/A - DUQUE DE CAXIAS	ESTRADA VENÂNCIO PEREIRA VELOSO, 556 - 	DUQUE DE CAXIAS	RJ
TRIUNFO LOGÍSTICA	AVENIDA CIDADE DE LIMA, 86 - 	RIO DE JANEIRO	RJ
TS USINAGEM E MANUTENÇÃO INDUSTRIAL LTDA	RUA GUIMARÃES JÚNIOR, 140 - 	JUIZ DE FORA	MG
TUBOS OLIVEIRA LTDA.	AVENIDA AMÂNCIO GAIOLLI, 1065 - 	GUARULHOS	SP
UMI SAN SERVICOS DE APOIO A NAVEGACAO E ENGENHARIA LTDA	RODOVIA DO SOL, 2780 - 	VILA VELHA	ES
UNICA RENTAL E LOGISTICA LTDA - ME	AVENIDA TENENTE JOSÉ EDUARDO, 39 - SALA 105	BARRA MANSA	RJ
UPTEC – CONSTRUÇÃO E TECNOLOGIA LTDA	RUA CRETA, 245 - 	Sabará	MG
UTE GNA II GERACAO DE ENERGIA S.A.	FAZ SACO DANTAS, S/N - 	SÃO JOÃO DA BARRA	RJ
UTIL REFRIGERACAO LTDA	AVENIDA DOM HÉLDER CÂMARA, 177 - 	RIO DE JANEIRO	RJ
V. C. FERRAGENS LTDA	RUA DO MATOSO, 132 - 	RIO DE JANEIRO	RJ
VALE  CPBS	ESTRADA ILHA DA MADEIRA, SN - 	ITAGUAÍ	RJ
VALE CTSS	RUA VINTE E UM, 209 - QUADRA 15B LOTE 01	Duque de Caxias	RJ
VALE S.A	PRAIA BOTAFOGO, 186 - SAL 701 , 1101 1601 1701 1801 1901	RIO DE JANEIRO	RJ
VALE SA - TERNIUM	AVENIDA JOÃO XXIII, SN - 	RIO DE JANEIRO	RJ
VALE TIG	OTR PRAIA DO LESTE, SN - ILHA DE GUAI	MANGARATIBA	RJ
VALGROUP BRASIL I INDUSTRIA DE EMBALAGENS PLASTICAS LTDA	ESTRADA BEIRA RIO, SN - 	DUQUE DE CAXIAS	RJ
VALGROUP RJ INDUSTRIA DE EMBALAGENS RIGIDAS LTDA	AVENIDA ANA DANTAS, SN - GALPAOG3 G5 G6 E G9	DUQUE DE CAXIAS	RJ
VERALLIA BRASIL S.A	AVENIDA ENGENHEIRO NICOLAU DE VERGUEIRO FORJAZ, 1960 - 	PORTO FERREIRA	SP
VERTICAL PARTS	RUA ARMANDINA BRAGA DE ALMEIDA, 383 - 	GUARULHOS	SP
VERTICAL SERVIÇOS ESPECIALIZADOS EM MANUTENÇÃO PREDIAL LTDA	AVENIDA DAS AMÉRICAS, 3333 - SALA 713	RIO DE JANEIRO	RJ
VETEL MONTAGENS INDUSTRIAIS LTDA	RUA JOSE PAOLILLO, 321 - SALA A	LIMEIRA	SP
VIBRA ENERGIA S.A	AVENIDA FABOR, S.N - 	DUQUE DE CAXIAS	RJ
VILLAGE PARTICIPACOES E EVENTOS LTDA	RUA RONALD TKOTZ, 8260 - SALA 1 LOTE 7-8E LOTE 7-8F LOTE 7-8G	CAMBÉ	PR
VILMA C LIMA PRESTADORA DE SERVICOS LTDA	AVENIDA PRINCESA ISABEL, 500 - 	RIO DE JANEIRO	RJ
VIPLACON INSTALACAO E MANUTENCAO DE PRODUTOS DE SEGURANCA LTDA	RUA IBITINGA, 142 - 	BARUERU	SP
VISIA	R DO GROTAO, 365 - 	IVOTI	RS
VISOLUX COMUNICACAO VISUAL	ROD PR 317 KM 01, S/N - 	MARINGA	PR
VITEC EQUIPAMENTOS INDUSTRIAIS LTDA	AVENIDA MONSENHOR MAURO VALLINI, 565 - 	SOROCABA	SP
VOE EVENTOS LTDA	RUA JOAO CARLOS DE SOUZA, 112 - SALA 01	FLORIANOPOLIS	SC
VS TRANSPORTES	RUA DOMICIANO RIBEIRO, 235 - GALPAO1	SAO PAULO	SP
W COSTA CONSTRUTORA	ROD AMARAL PEIXOTO, S/N - KM 21 LOTE 11 QUADRAA SALA 102	MARICA	RJ
WALPESCADOS TRANSPORTE E COMERCIO ME	AVENIDA ALMIRANTE BARROSO, 1133 - SALA B	CABO FRIO	RJ
WEG EQUIPAMENTOS ELETRICOS S/A	RUA DOUTOR PEDRO ZIMMERMANN, 6751 - BLOCO A	BLUMENAU	SC
WM MANUTENCAO E REPARACAO DE MAQUINAS, PRODUTOS E EQUIPAMENTOS LTDA	RUA JOÃO CHAGAS ORTINS DE FREITAS, 577 - LOTE 06 A 09 SALA 404	Lauro de Freitas	BA
WORLD SINALIZE E DECORE EIRELI	RUA AUGUSTO PIACENTINI, 134 - 	SÃO PAULO	SP
ZEITTEC SOLUCOES EM CONECTIVIDADE LTDA	RUA LAMENHA LINS, 2154 - 	Curitiba	PR
ZOPONE ENGENHARIA E COMERCIO LTDA	AVENIDA RODRIGUES ALVES, 34-53 - 	BAURU	SP`;

async function upload() {
  const lines = rawData.trim().split('\n');
  const clientes = lines.map(line => {
    const [nome, endereco, cidade, estado] = line.split('\t').map(s => s ? s.trim() : '');
    return { nome, endereco, cidade, estado };
  }).filter(c => c.nome);

  console.log(`Encontrados ${clientes.length} clientes para inserir.`);
  
  // Insert in batches of 100
  let inserted = 0;
  for (let i = 0; i < clientes.length; i += 100) {
    const batch = clientes.slice(i, i + 100);
    const { data, error } = await supabase.from('clientes').insert(batch);
    if (error) {
      console.error('Erro ao inserir o lote:', error);
    } else {
      inserted += batch.length;
      console.log(`Inseridos ${inserted} de ${clientes.length}...`);
    }
  }
  console.log('Upload completo!');
}

upload();
